// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ssnEUehh_fxl5PITXhQFZ6R3YpsPJhQ',
    appId: '1:988732238017:web:2483d153e01c94d7ff0c40',
    messagingSenderId: '988732238017',
    projectId: 'blueart-14b4b',
    authDomain: 'blueart-14b4b.firebaseapp.com',
    storageBucket: 'blueart-14b4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBMkHGERz-8ULcHjj2TZjm2qWiwvnPJIM',
    appId: '1:988732238017:android:c74e1c86ded9f759ff0c40',
    messagingSenderId: '988732238017',
    projectId: 'blueart-14b4b',
    storageBucket: 'blueart-14b4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALQxCxA-mQWQUAAV6liP0wP-6dfKm3rgk',
    appId: '1:988732238017:ios:b8f2be211104c346ff0c40',
    messagingSenderId: '988732238017',
    projectId: 'blueart-14b4b',
    storageBucket: 'blueart-14b4b.firebasestorage.app',
    iosClientId: '988732238017-nbhptji92f1i7ti2bbh5tqf9evl4lh9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.blueArtMad2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALQxCxA-mQWQUAAV6liP0wP-6dfKm3rgk',
    appId: '1:988732238017:ios:b8f2be211104c346ff0c40',
    messagingSenderId: '988732238017',
    projectId: 'blueart-14b4b',
    storageBucket: 'blueart-14b4b.firebasestorage.app',
    iosClientId: '988732238017-nbhptji92f1i7ti2bbh5tqf9evl4lh9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.blueArtMad2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5ssnEUehh_fxl5PITXhQFZ6R3YpsPJhQ',
    appId: '1:988732238017:web:e6cd5719c66d0778ff0c40',
    messagingSenderId: '988732238017',
    projectId: 'blueart-14b4b',
    authDomain: 'blueart-14b4b.firebaseapp.com',
    storageBucket: 'blueart-14b4b.firebasestorage.app',
  );

}